"""
PDF Report Generation Tool

Converts markdown content to professional PDF reports with embedded images.
"""

from langchain_core.tools import tool
import markdown
from weasyprint import HTML, CSS
from datetime import datetime
import os
from pathlib import Path


@tool
def generate_pdf_report(
    markdown_content: str,
    output_filename: str = "report.pdf",
    title: str = "Research Report",
    author: str = "Deep Research Agent"
) -> str:
    """
    Generate a professional PDF report from markdown content.

    This tool converts markdown text (including embedded images) into a styled PDF document.
    Images should be referenced using standard markdown syntax: ![alt text](path/to/image.png)

    Args:
        markdown_content: The markdown-formatted content for the report. Can include:
            - Headers (# ## ###)
            - Lists (- or 1.)
            - Bold (**text**) and italic (*text*)
            - Links [text](url)
            - Images ![alt](path)
            - Code blocks (```)
            - Tables
        output_filename: Name for the output PDF file (default: report.pdf)
        title: Title to display on the report cover page
        author: Author name to display on the report

    Returns:
        str: Path to the generated PDF file (in /scratchpad/reports/)

    Example:
        markdown_content = '''
        # Executive Summary

        Key findings from the analysis...

        ## Market Analysis

        ![Price Chart](scratchpad/plots/price_chart.png)

        - Finding 1
        - Finding 2

        ## Sources
        - [Source 1](https://example.com)
        '''

        result = generate_pdf_report(
            markdown_content=markdown_content,
            output_filename="market_report.pdf",
            title="48-Hour Market Impact Report"
        )
    """
    try:
        # Ensure output directory exists
        output_dir = Path("/scratchpad/reports")
        output_dir.mkdir(parents=True, exist_ok=True)

        # Create full output path
        output_path = output_dir / output_filename

        # Convert markdown to HTML
        html_content = markdown.markdown(
            markdown_content,
            extensions=[
                'tables',
                'fenced_code',
                'codehilite',
                'nl2br',
                'sane_lists'
            ]
        )

        # Get current date
        current_date = datetime.now().strftime("%B %d, %Y")

        # Create styled HTML document
        full_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>{title}</title>
        </head>
        <body>
            <div class="cover-page">
                <h1 class="report-title">{title}</h1>
                <p class="report-meta">Generated by: {author}</p>
                <p class="report-meta">Date: {current_date}</p>
            </div>

            <div class="content">
                {html_content}
            </div>
        </body>
        </html>
        """

        # CSS styling for professional appearance
        css_styles = CSS(string="""
            @page {
                size: A4;
                margin: 2.5cm 2cm;

                @top-right {
                    content: "Page " counter(page) " of " counter(pages);
                    font-size: 9pt;
                    color: #666;
                }

                @bottom-center {
                    content: string(report-title);
                    font-size: 9pt;
                    color: #666;
                }
            }

            body {
                font-family: 'Helvetica', 'Arial', sans-serif;
                line-height: 1.6;
                color: #333;
            }

            .cover-page {
                page-break-after: always;
                text-align: center;
                padding-top: 40%;
            }

            .report-title {
                font-size: 32pt;
                font-weight: bold;
                color: #1a1a1a;
                margin-bottom: 30px;
                string-set: report-title content();
            }

            .report-meta {
                font-size: 14pt;
                color: #666;
                margin: 10px 0;
            }

            .content {
                page-break-before: always;
            }

            h1 {
                font-size: 24pt;
                color: #1a1a1a;
                margin-top: 30px;
                margin-bottom: 15px;
                border-bottom: 2px solid #333;
                padding-bottom: 5px;
                page-break-after: avoid;
            }

            h2 {
                font-size: 18pt;
                color: #2a2a2a;
                margin-top: 25px;
                margin-bottom: 12px;
                page-break-after: avoid;
            }

            h3 {
                font-size: 14pt;
                color: #3a3a3a;
                margin-top: 20px;
                margin-bottom: 10px;
                page-break-after: avoid;
            }

            p {
                margin-bottom: 10px;
                text-align: justify;
            }

            img {
                max-width: 100%;
                height: auto;
                display: block;
                margin: 20px auto;
                page-break-inside: avoid;
            }

            ul, ol {
                margin-bottom: 15px;
                padding-left: 30px;
            }

            li {
                margin-bottom: 5px;
            }

            a {
                color: #0066cc;
                text-decoration: none;
            }

            a:hover {
                text-decoration: underline;
            }

            table {
                width: 100%;
                border-collapse: collapse;
                margin: 20px 0;
                page-break-inside: avoid;
            }

            th, td {
                border: 1px solid #ddd;
                padding: 10px;
                text-align: left;
            }

            th {
                background-color: #f5f5f5;
                font-weight: bold;
            }

            code {
                background-color: #f5f5f5;
                padding: 2px 5px;
                border-radius: 3px;
                font-family: 'Courier New', monospace;
                font-size: 10pt;
            }

            pre {
                background-color: #f5f5f5;
                padding: 15px;
                border-radius: 5px;
                overflow-x: auto;
                page-break-inside: avoid;
            }

            pre code {
                background-color: transparent;
                padding: 0;
            }

            blockquote {
                border-left: 4px solid #ccc;
                margin-left: 0;
                padding-left: 20px;
                color: #666;
                font-style: italic;
            }
        """)

        # Generate PDF
        HTML(string=full_html).write_pdf(
            str(output_path),
            stylesheets=[css_styles]
        )

        return f"PDF report successfully generated at: scratchpad/reports/{output_filename}"

    except Exception as e:
        return f"Error generating PDF: {str(e)}"
